name: Broken C3 Pipeline

on:
  push:
    branches: main  # ERROR: Missing []

jobs:
  build:
    runs-on: ubuntu  # ERROR: Invalid runner tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        # ERROR: No dependencies installed, this will fail
        run: pytest -v 

    # ERROR: This line is unindented and has no Job ID
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        # ERROR: Missing '-' and '.' context
        run: docker build t myapp
